### ISSUE TITLE
section6の作成

### ISSUE THREAD

**Issue by iimura0728** [namitarox/pixtech_nishihara#19]
# 作成するパーツ
section6

![section6](https://user-images.githubusercontent.com/25382428/73117616-b4876e80-3f8b-11ea-86c1-d7706d88fa99.png)

# 対応するブランチ
ここに対応するブランチを記載
feature/section6

**Comment by snj9sincostan** [comment]
<h1>作成するパーツ</h1>
section6

<h1>対応するブランチ</h1>
feature/section6

**Comment by snj9sincostan** [comment]
完了済

**Comment by snj9sincostan** [comment]
完了済
