### ISSUE TITLE
headerのナビゲーションの縦を揃える

### ISSUE THREAD

**Issue by namitarox** [namitarox/pixtech_nishihara#8]
# 概要
![スクリーンショット 2020-03-05 1 17 16](https://user-images.githubusercontent.com/25382428/75899761-4afa5a00-5e7f-11ea-9268-445151b6bd9d.png)

ナビゲーションの縦がそろってないので修正してください

# 対応するブランチ
issue/fix-nav

**Comment by snj9sincostan** [comment]
自分のコードを確認した所ナビゲーションのズレは確認できませんでした！
ローカルのブランチを全て切り替えて見てみたのですがやはり見当たりません。
